services:
   next:
      image: node:21
      container_name: next
      volumes:
        - ./ui/the-eye:/next-app
      ports:
        - "80:3000"
      networks:
         - datagetta_net
      working_dir: /next-app
      entrypoint: ["/bin/sh","-c"]
      command:
      - |
         npm ci
         npm run build
         npm run start
   postgres:
      image: postgres:16
      container_name: postgres
      volumes:
        - ./backups:/backups
      env_file:
        - db.env
      networks:
         - datagetta_net

networks:
   datagetta_net:
      driver: bridge
