INSERT INTO conferences
VALUES
('American East Conference'),
('American Athletic Conference'),
('Atlantic 10 Conference'),
('Atlantic Coast Conference'),
('Atlantic Sun Conference'),
('Big 12 Conference'),
('Big East Conference'),
('Big South Conference'),
('Big Ten Conference'),
('Big West Conference'),
('Coastal Athletic Association'),
('Conference USA'),
('Horizon League'),
('Metro Atlantic Athletic Conference'),
('Mid-American Conference'),
('Missouri Valley Conference'),
('Mountain West Conference'),
('Northeast Conference'),
('Ohio Valley Conference'),
('PAC-12 Conference'),
('Patriot League'),
('Southeastern Conference'),
('Southern Conference'),
('Southland Conference'),
('Southwestern Athletic Conference'),
('Sun Belt Conference'),
('The Ivy League'),
('The Summit League'),
('West Coast Conference'),
('Western Athletic Conference');