INSERT INTO conferences
VALUES
('Southeastern Conference'),
('Atlantic Coast Conference'),
('Big 12 Conference'),
('Big Ten Conference'),
('PAC-12 Conference'),
('American East Conference'),
('American Athletic Conference'),
('Atlantic 10 Conference'),
('Atlantic Sun Conference'),
('Big East Conference'),
('Big South Conference'),
('Big West Conference'),
('Coastal Athletic Association'),
('Conference USA'),
('Horizon League'),
('Metro Atlantic Athletic Conference'),
('Mid-American Conference'),
('Missouri Valley Conference'),
('Mountain West Conference'),
('Northeast Conference'),
('Ohio Valley Conference'),
('Patriot League'),
('Southern Conference'),
('Southland Conference'),
('Southwestern Athletic Conference'),
('Sun Belt Conference'),
('The Ivy League'),
('The Summit League'),
('West Coast Conference'),
('Western Athletic Conference');